server:
   port: 8080      
clients:
  data: http://172.31.25.151:8080
  training: http://172.31.90.235:5000
  events: http://ip-172-31-40-214.ec2.internal:8080
  players: http://ip-172-31-42-43.ec2.internal:8080

connection:
  details:
   host: '172.31.7.99'
   port: 27017
   database: 'predictor-db'
   username: 'predictor'
   password: '{cipher}3af0dbc153aca8924d1f0588f393c91b55a5be05ec296093fd5694d11b65ddb3'

spring:
  data:
   mongodb:
    uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1


training:
  evaluation: false
