server:
  port: 8080       
clients:
 data: http://172.31.25.151:8080
 training: http://172.31.30.98:5000
 message: http://172.31.10.169:8080

connection:
  details:
   host: '172.31.7.99'
   port: 27017
   database: 'predictor-db'
   username: 'predictor'
   password: '{cipher}3af0dbc153aca8924d1f0588f393c91b55a5be05ec296093fd5694d11b65ddb3'

spring:
  data:
   mongodb:
    uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1


