server:
  port: 8080      

clients:
  data-scraper: http://172.31.31.152:8080
  events-scraper: http://172.31.7.64:8080
  data: http://172.31.25.151:8080
  data-event: http://172.31.4.5:8080
  teams: http://172.31.83.206:8080
  players: http://172.31.25.243:8080
  team-events: http://172.31.85.150:8080
  player-events: http://172.31.90.17:8080
  client: http://172.31.82.12:8080

connection:
  details:
   host: '172.31.7.99'
   port: 27017
   database: 'predictor-db'
   username: 'predictor'
   password: '{cipher}3af0dbc153aca8924d1f0588f393c91b55a5be05ec296093fd5694d11b65ddb3'

spring:
  data:
   mongodb:
    uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1

test:
  mode: false
          

